In [89]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from nltk.tokenize import word_tokenize
import nltk
from collections import Counter
import pandas as pd

In [90]:
document = """
The quick brown fox jumps over the lazy dog. The dog was sleeping under a tree. 
A tree provides shade on a sunny day. The day was bright and beautiful. 
Beautiful flowers bloom in the spring. Spring brings new life to the garden. 
The garden has many colorful plants. Plants need water and sunlight to grow. 
To grow strong, they require proper care. Proper care includes regular watering. 
Watering should be done in the morning. The morning sun is gentle and warm. 
Warm weather makes people happy. Happy children play in the park. 
The park is full of laughter and joy. Joy spreads when friends are together. 
Together they explore new adventures. Adventures make life exciting and fun. 
Fun times create lasting memories. Memories are treasures we keep forever.

Machine learning is a powerful tool for solving complex problems. Complex problems require innovative solutions.
Solutions often come from careful analysis of data. Data is the foundation of modern artificial intelligence.
Artificial intelligence is transforming industries across the world. The world is becoming more connected every day.
Every day brings new opportunities to learn. Learning is a lifelong journey of discovery.
Discovery leads to innovation and progress. Progress requires dedication and hard work.
Hard work pays off in the long run. The long run requires patience and persistence.

Python is a popular programming language for data science. Data science involves analyzing large datasets.
Large datasets contain valuable insights and patterns. Patterns help us understand complex phenomena.
Complex phenomena can be modeled using neural networks. Neural networks learn from examples and experience.
Experience teaches us important lessons about life. Life is full of challenges and opportunities.
Opportunities arise when we least expect them. We must be prepared to seize the moment.
The moment we decide to act determines our future. Our future depends on the choices we make today.

Technology is rapidly evolving in the modern era. The modern era is characterized by digital transformation.
Digital transformation is changing how businesses operate. Businesses must adapt to stay competitive in the market.
The market demands innovation and efficiency. Efficiency can be improved through automation and optimization.
Optimization techniques help maximize performance and results. Results are what matter most in business.
Business success requires strategic planning and execution. Execution is where ideas become reality.
Reality often differs from our expectations. Expectations should be based on realistic assumptions.

Education is the key to personal growth. Personal growth requires self-reflection and improvement.
Improvement comes from learning new skills and knowledge. Knowledge is power in the information age.
The information age has revolutionized communication. Communication is essential for human connection.
Human connection brings meaning to our lives. Our lives are shaped by the relationships we build.
We build relationships through trust and respect. Respect is earned through consistent actions.
Actions speak louder than words in all situations. All situations require careful consideration before acting.

Nature is a source of inspiration and wonder. Wonder fills us with curiosity about the universe.
The universe is vast and full of mysteries. Mysteries challenge us to think deeply.
Thinking deeply helps us understand ourselves better. Understanding ourselves is the first step to wisdom.
Wisdom comes from experience and reflection. Reflection allows us to learn from our mistakes.
Our mistakes are valuable teachers in life. Life teaches us lessons through both success and failure.
Failure is not the opposite of success. Success is built on a foundation of failures.

The ocean is home to countless species of marine life. Marine life includes fish, whales, and dolphins.
Dolphins are intelligent and social creatures. Creatures in the ocean have adapted to their environment.
Their environment is constantly changing and dynamic. Dynamic systems require continuous monitoring and adjustment.
Adjustment is necessary when conditions change. Change is the only constant in life.
In life, we must learn to embrace uncertainty. Uncertainty can be uncomfortable but also exciting.
Exciting opportunities often come with some risk. Risk management is important in decision making.

Books are windows into different worlds and perspectives. Perspectives shape how we see reality.
Reality is subjective and depends on individual experience. Individual experience varies from person to person.
From person to person, we can learn valuable lessons. Lessons learned help us grow wiser.
Wiser people make better decisions overall. Overall, wisdom improves quality of life.
Quality of life depends on many factors. Factors include health, relationships, and purpose.
Purpose gives meaning to our daily activities. Activities should align with our core values.

Music has the power to evoke strong emotions. Emotions influence our thoughts and behaviors.
Behaviors can be changed through conscious effort. Effort is required to achieve any goal.
Any goal worth pursuing takes time to accomplish. To accomplish great things requires perseverance.
Perseverance is the ability to keep going. Keep going even when times are tough.
Tough times don't last but tough people do. People who persist eventually reach their destination.
Their destination may be different than originally planned. Originally planned paths sometimes need adjustment.

Exercise is important for maintaining good health. Good health contributes to overall wellbeing.
Wellbeing encompasses physical, mental, and emotional health. Mental health is just as important as physical health.
Physical health can be improved through regular activity. Regular activity includes walking, running, and swimming.
Swimming is a low-impact form of exercise. Exercise releases endorphins that improve mood.
Mood affects how we perceive the world. The world looks different depending on our state of mind.
Our state of mind can be influenced by thoughts. Thoughts have power to shape our reality.

Dreams inspire us to reach for something greater. Something greater than ourselves gives life purpose.
Life purpose drives us forward each day. Each day is a new opportunity to grow.
To grow requires stepping outside comfort zones. Comfort zones limit our potential for development.
Development happens when we challenge ourselves. Ourselves and our capabilities are often underestimated.
Underestimated people can surprise everyone around them. Around them, others begin to see new possibilities.
New possibilities emerge when we think creatively. Creatively solving problems leads to innovation.

Food brings people together across cultures. Across cultures, certain values remain universal.
Universal values include love, kindness, and compassion. Compassion helps us connect with others.
Others benefit when we show empathy and understanding. Understanding different viewpoints enriches our perspective.
Our perspective broadens through travel and exploration. Exploration satisfies our innate curiosity about the world.
The world offers endless opportunities for adventure. Adventure awaits those who dare to seek it.
To seek new experiences requires courage and openness. Openness to new ideas fosters personal growth.

Time is our most valuable resource. Resources should be used wisely and efficiently.
Efficiently managing time leads to greater productivity. Productivity increases when we focus on priorities.
Priorities should reflect our deepest values. Values guide our decisions and actions.
Actions create the life we want to live. To live fully means embracing each moment.
Each moment is precious and unrepeatable. Unrepeatable experiences make life memorable and rich.
Rich experiences come from genuine connections with others. Others help us see ourselves more clearly.

Creativity flourishes when we give ourselves permission to experiment. To experiment means accepting the possibility of failure.
Failure provides feedback for improvement and learning. Learning from mistakes accelerates progress significantly.
Significantly better outcomes result from continuous refinement. Refinement is an iterative process of improvement.
Improvement never ends for those committed to excellence. Excellence is achieved through dedication and practice.
Practice makes progress, not necessarily perfection. Perfection is an ideal that inspires us forward.
Forward movement is what matters most in the journey. The journey itself is more important than the destination.
"""

In [91]:
tokens = word_tokenize(document.lower())

In [92]:
vocab = {'<UNK>':0}

for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]=len(vocab)
        
print(len(vocab))

530


In [93]:
input_sentences = document.split('\n')

In [94]:
def text_to_indices(sentence, vocab):
    # tokens = word_tokenize(text)
    result = []
    for token in sentence:
        if token in vocab:
            result.append(vocab[token])
        else:
            result.append(vocab['<UNK>'])
    
    return result

In [95]:
input_numerical_sentences = []
for sentence in input_sentences:
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [96]:
training_sequence = []
for sentence in input_numerical_sentences:
    for i in range(1,len(sentence)):
        training_sequence.append(sentence[:i+1])

In [97]:
len_list = []
for sentence in training_sequence:
    len_list.append(len(sentence))

In [98]:
max(len_list)

21

In [99]:
padded_training_sequence = []
for sequence in training_sequence:
    padded_training_sequence.append([0]*(21-len(sequence))+sequence)

In [100]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [101]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0,   0,  ..., 157, 249,   1],
        [  0,   0, 423,  ..., 249,   1, 383],
        [  0, 423, 527,  ...,   1, 383,   9]])

In [102]:
X = padded_training_sequence[:,:-1]
y = padded_training_sequence[:,-1]

In [103]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0,   0,  ..., 111, 157, 249],
        [  0,   0, 423,  ..., 157, 249,   1],
        [  0, 423, 527,  ..., 249,   1, 383]])

In [104]:
y

tensor([  2,   3,   4,  ...,   1, 383,   9])

In [105]:
class CustomDataset(Dataset):
    def __init__(self,X,y):
        self.X = X
        self.y = y
    def __len__(self):
        return self.X.shape[0]
    def __getitem__(self, index):
        return self.X[index],self.y[index]

In [106]:
dataset = CustomDataset(X,y)

In [107]:
len(dataset)

1361

In [108]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [109]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [110]:
class LSTMModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,100)
        self.lstm = nn.LSTM(100,150,batch_first=True)
        self.fc = nn.Linear(150,vocab_size)
    def forward(self,x):
        embedded = self.embedding(x)
        intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state).squeeze(0)
        return output

In [111]:
model = LSTMModel(len(vocab))

In [112]:
device = torch.device('cuda')

In [113]:
model.to(device)

LSTMModel(
  (embedding): Embedding(530, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=530, bias=True)
)

In [114]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [115]:
for epoch in range(epochs):
    total_loss = 0
    for batch_x, batch_y in dataloader:
        batch_x,batch_y = batch_x.to(device),batch_y.to(device)
        
        optimizer.zero_grad()
        
        output = model(batch_x)
        
        loss = criterion(output,batch_y)
        
        loss.backward()
        
        optimizer.step()
        
        total_loss+=loss.item()
        
    print(f"Epoch: {epoch+1}, Avg Loss: {total_loss/len(batch_x)}")

Epoch: 1, Avg Loss: 15.357909146477194
Epoch: 2, Avg Loss: 13.38002908931059
Epoch: 3, Avg Loss: 12.424948692321777
Epoch: 4, Avg Loss: 11.452746798010434
Epoch: 3, Avg Loss: 12.424948692321777
Epoch: 4, Avg Loss: 11.452746798010434
Epoch: 5, Avg Loss: 10.435917728087482
Epoch: 6, Avg Loss: 9.366511302835802
Epoch: 5, Avg Loss: 10.435917728087482
Epoch: 6, Avg Loss: 9.366511302835802
Epoch: 7, Avg Loss: 8.32980843151317
Epoch: 8, Avg Loss: 7.383516269571641
Epoch: 7, Avg Loss: 8.32980843151317
Epoch: 8, Avg Loss: 7.383516269571641
Epoch: 9, Avg Loss: 6.432085850659539
Epoch: 10, Avg Loss: 5.559761292794171
Epoch: 9, Avg Loss: 6.432085850659539
Epoch: 10, Avg Loss: 5.559761292794171
Epoch: 11, Avg Loss: 4.754843333188226
Epoch: 12, Avg Loss: 4.048045018140008
Epoch: 11, Avg Loss: 4.754843333188226
Epoch: 12, Avg Loss: 4.048045018140008
Epoch: 13, Avg Loss: 3.426171429017011
Epoch: 14, Avg Loss: 2.8928027433507584
Epoch: 13, Avg Loss: 3.426171429017011
Epoch: 14, Avg Loss: 2.892802743350

In [116]:
def predict(model,vocab, text):
    
    tokenized_text = word_tokenize(text.lower())
    
    numerical_text = text_to_indices(tokenized_text,vocab)
    
    padded_text = torch.tensor([0]*(21-len(numerical_text)) + numerical_text,dtype=torch.long).unsqueeze(0)
    
    padded_text = padded_text.to(device)  # Move tensor to GPU
    
    output = model(padded_text)
    
    value,index = torch.max(output, dim=1)
    
    return text+ " "+list(vocab.keys())[index]

In [117]:
predict(model, vocab,'A tree provides')

'A tree provides shade'

In [120]:
num_tokens = 10
input_text = 'Hi'
for i in range(num_tokens):
    output = predict(model,vocab,input_text)
    print(output)
    input_text=output

Hi has
Hi has the
Hi has the power
Hi has the power to
Hi has the power to evoke
Hi has the power to evoke strong
Hi has the power to evoke strong emotions
Hi has the power to evoke strong emotions .
Hi has the power to evoke strong emotions . emotions
Hi has the power to evoke strong emotions . emotions influence
